---
- name: Test ONTAP connectivity
  hosts: ontap
  gather_facts: no
  connection: local
  collections:
    - netapp.ontap

  tasks:
    - name: Get cluster info
      na_ontap_rest_info:
        hostname: "{{ ansible_host }}"
        username: "{{ ontap_username }}"
        password: "{{ ontap_password }}"
        https: "{{ ontap_https }}"
        validate_certs: "{{ ontap_validate_certs }}"



