---
- name: Create NetApp Volume
  hosts: ontap
  connection: local
  collections:
    - netapp.ontap
  tasks:
    - name: Create volume
      na_ontap_volume:
        state: present
        name: ansible_vol_01
        size: 30
        size_unit: mb
        aggregate_name: aggr1
        vserver: "{{ ontap_vserver }}"
        hostname: "{{ ontap_hostname }}"
        username: "{{ ontap_username }}"
        password: "{{ ontap_password }}"
        https: "{{ ontap_https }}"
        validate_certs: "{{ ontap_validate_certs }}"