apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z {{ .Values.mysql.host }} {{ .Values.mysql.port }}; do
                echo "Waiting for MySQL..."
                sleep 3
              done
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_HOST
              value: {{ .Values.mysql.host }}
            - name: DB_PORT
              value: "{{ .Values.mysql.port }}"
            - name: DB_NAME
              value: {{ .Values.mysql.database }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.existingSecret }}
                  key: mysql-username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.existingSecret }}
                  key: mysql-root-password