# Provision
- src: git@gitlab.yoyoyo.net:ansible-library/roles/vm-provision.git
  scm: git
  version: "master"
  name: vm-provision

# Base
- src: git@gitlab.yoyoyo.net:ansible-library/roles/common.git
  scm: git
  version: "master"
  name: common
- src: git@gitlab.yoyoyo.net:ansible-library/roles/user_management.git
  scm: git
  version: "master"
  name: user_management

# Security
- src: git@gitlab.yoyoyo.net:ansible-library/roles/sentinelone.git
  scm: git
  version: "master"
  name: sentinelone

- src: git@gitlab.yoyoyo.net:ansible-library/roles/jdk.git
  scm: git
  version: "master"
  name: jdk

# Monitoring
- src: git@gitlab.yoyoyo.net:ansible-library/roles/filebeat.git
  scm: git
  version: "master"
  name: filebeat
- src: git@gitlab.yoyoyo.net:ansible-library/roles/node_exporter.git
  scm: git
  version: "master"
  name: node_exporter
- src: git@gitlab.yoyoyo.net:ansible-library/roles/logstash.git
  scm: git
  version: "master"
  name: logstash
- src: git@gitlab.yoyoyo.net:ansible-library/roles/telegraph.git
  scm: git
  version: "master"
  name: telegraph