---
- name: Install GitLab CE
  hosts: gitlab
  become: true

  vars:
    gitlab_external_url: "http://gitlab.sunny.lab"

 tasks:

    - name: Update system packages
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install dependencies
      dnf:
        name:
          - curl
          - policycoreutils
          - openssh-server
          - perl
          - postfix
        state: present

    - name: Enable SSH service
      service:
        name: sshd
        state: started
        enabled: true

    - name: Enable postfix
      service:
        name: postfix
        state: started
        enabled: true

    - name: Add GitLab CE repository (RPM)
      shell: |
        curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | bash
      args:
        creates: /etc/yum.repos.d/gitlab_gitlab-ce.repo

    - name: Install GitLab CE
      environment:
        EXTERNAL_URL: "{{ gitlab_external_url }}"
      dnf:
        name: gitlab-ce
        state: present

    - name: Reconfigure GitLab
      command: gitlab-ctl reconfigure

    - name: Check GitLab status
      command: gitlab-ctl status
      register: gitlab_status
      changed_when: false

    - name: Show status
      debug:
        var: gitlab_status.stdout_lines