---
- name: Add Prometheus Helm repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
    state: present
  delegate_to: localhost
  become: no


- name: Debug variables
  debug:
    msg:
      - "Namespace: {{ monitoring_namespace }}"
      - "StorageClass: {{ storage_class }}"
      - "Kubeconfig: {{ kubeconfig_path }}"
  delegate_to: localhost

- name: Create monitoring namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ monitoring_namespace }}"
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
  delegate_to: localhost

- name: Deploy kube-prometheus-stack
  kubernetes.core.helm:
    name: "{{ prometheus_helm_release }}"
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: "{{ monitoring_namespace }}"
    create_namespace: false
    values_files:
      - "{{ prometheus_values_file }}"
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
  delegate_to: localhost
