---
- name: Add Prometheus Helm repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Debug monitoring_namespace
  debug:
    var: monitoring_namespace

- name: Create monitoring namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ monitoring_namespace }}"
    state: present

- name: Template values.yaml
  template:
    src: values.yaml.j2
    dest: /tmp/monitoring-values.yaml

- name: Deploy kube-prometheus-stack
  kubernetes.core.helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: "{{ monitoring_namespace }}"
    values_files:
      - /tmp/monitoring-values.yaml
    state: present
