---
# Source: flaskapp/templates/networkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: myapp-flaskapp
spec:
  podSelector:
    matchLabels:
      app: flaskapp
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
---
# Source: flaskapp/charts/mysql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-mysql
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.4.0
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/managed-by: Helm
  annotations:
automountServiceAccountToken: true
secrets:
  - name: myapp-mysql
---
# Source: flaskapp/charts/mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: myapp-mysql
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.4.0
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mysql-root-password: "b1hTZmlITUxzSA=="
  mysql-password: "M1FldmFISDhRWA=="
---
# Source: flaskapp/charts/mysql/templates/primary/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-mysql
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.4.0
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
data:
  my.cnf: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    slow_query_log=0
    slow_query_log_file=/opt/bitnami/mysql/logs/mysqld.log
    long_query_time=10.0
    
    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    
    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
---
# Source: flaskapp/charts/mysql/templates/primary/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp-mysql-headless
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.4.0
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector: 
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/component: primary
---
# Source: flaskapp/charts/mysql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp-mysql
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.4.0
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
      nodePort: null
  selector: 
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/component: primary
---
# Source: flaskapp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp-flaskapp
  labels:
    helm.sh/chart: flaskapp-0.1.0
    app.kubernetes.io/name: flaskapp
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app.kubernetes.io/name: flaskapp
    app.kubernetes.io/instance: myapp
---
# Source: flaskapp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: flaskapp
              topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              until nc -z -v -w30 myapp-mysql 3306; do
                echo "Waiting for MySQL..."
                sleep 5
              done
      containers:
        - name: flaskapp
          image: "sundayfagbuaro/flask-helm-deploy-img:1"
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: myapp-mysql

            - name: DB_NAME
              value: users_db

            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: myapp-db-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: myapp-db-secret
                  key: DB_PASS
        

#          env:
#            - name: DB_USER
#              valueFrom:
#                secretKeyRef:
#                  name: myapp-db-secret
#                  key: DB_USER
#            - name: DB_PASS
#                secretKeyRef:
##              valueFrom:
#                  name: myapp-db-secret
#                  key: DB_PASS

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
---
# Source: flaskapp/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-flaskapp
  labels:
    helm.sh/chart: flaskapp-0.1.0
    app.kubernetes.io/name: flaskapp
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-flaskapp
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
# Source: flaskapp/charts/mysql/templates/primary/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp-mysql
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.4.0
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
spec:
  replicas: 1
  podManagementPolicy: ""
  selector:
    matchLabels: 
      app.kubernetes.io/name: mysql
      app.kubernetes.io/instance: myapp
      app.kubernetes.io/component: primary
  serviceName: myapp-mysql
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/configuration: 8f39c909e9422e00be8fd0daccc465ab7c84ecf7b453d730f7dce2b2e45418c9
      labels:
        app.kubernetes.io/name: mysql
        helm.sh/chart: mysql-9.4.0
        app.kubernetes.io/instance: myapp
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: primary
    spec:
      serviceAccountName: myapp-mysql
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: mysql
                    app.kubernetes.io/instance: myapp
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      initContainers:
      containers:
        - name: mysql
          image: docker.io/bitnami/mysql:8.0.30-debian-11-r27
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: myapp-mysql
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: "my_database"
          envFrom:
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          startupProbe:
            failureThreshold: 10
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          resources: 
            limits: {}
            requests: {}
          volumeMounts:
            - name: data
              mountPath: /bitnami/mysql
            - name: config
              mountPath: /opt/bitnami/mysql/conf/my.cnf
              subPath: my.cnf
      volumes:
        - name: config
          configMap:
            name: myapp-mysql
#  volumeClaimTemplates:
#    - metadata:
#        name: data
#        labels:
#          app.kubernetes.io/name: mysql
#          app.kubernetes.io/instance: myapp
#          app.kubernetes.io/component: primary
#      spec:
#        accessModes:
#          - ReadWriteOnce
#        resources:
#          requests:
#            storage: 8Gi
#        storageClassName: nfs-csi-databases  # <-- direct value
---
# Source: flaskapp/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-flaskapp
spec:
  ingressClassName: nginx
  rules:
    - host: containers.sunny.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myapp-flaskapp
                port:
                  number: 5000
---
# Source: flaskapp/templates/db-init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: myapp-flaskapp-db-init-1772224945
  namespace: default
  labels:
    app.kubernetes.io/name: flaskapp
    app.kubernetes.io/instance: myapp
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flaskapp
        app.kubernetes.io/instance: myapp
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-secret
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for secret to appear..."
              while [ ! -f /etc/secrets/DB_USER ]; do
                sleep 2
              done
              echo "Secret found!"
          volumeMounts:
            - name: db-secret
              mountPath: /etc/secrets
              readOnly: true
      containers:
        - name: db-init
          image: mysql:8.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL to be ready..."
              until mysqladmin ping \
                -h myapp-mysql \
                -u"$DB_USER" \
                -p"$DB_PASS" \
                --silent; do
                echo "MySQL not ready, sleeping..."
                sleep 3
              done

              echo "Creating database and table if not exists"
              mysql -h myapp-mysql \
                    -u $DB_USER -p$DB_PASS \
                    -e "CREATE DATABASE IF NOT EXISTS users_db; USE users_db; 
                       CREATE TABLE IF NOT EXISTS new_users (
                         id INT PRIMARY KEY AUTO_INCREMENT,
                         f_name VARCHAR(50),
                         l_name VARCHAR(50),
                         address VARCHAR(50),
                         phone VARCHAR(50),
                         username VARCHAR(50),
                         password VARCHAR(50),
                         email VARCHAR(50)
                       );"

              echo "Database initialization complete."
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: myapp-db-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: myapp-db-secret
                  key: DB_PASS
          volumeMounts:
            - name: db-secret
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: db-secret
          secret:
            secretName: myapp-db-secret
