replicaCount: 1

image:
  repository: sundayfagbuaro/flask-helm-deploy-img
  tag: 1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  host: containers.sunny.lab
  service: myapp-flaskapp
  port: 5000

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

database:
  host: myapp-mysql
  name: users_db
  port: 3306
  secretName: myapp-db-secret
  secretUserKey: DB_USER
  secretPasswordKey: DB_PASS

  mysql:
    auth:
      rootPassword: password        # Root password for MySQL
      database: users_db            # Database to auto-create
      username: flaskuser           # MySQL user
      password: password            # Password for the MySQL user
    
    image:
      registry: docker.io
      repository: bitnami/mysql
      tag: 8.0.33-debian-11-r0        # Valid image tag
      pullPolicy: IfNotPresent
    
    primary:
      persistence:
        enabled: true
        storageClass: nfs-csi-databases
        size: 8Gi
        accessModes:
         - ReadWriteOnce
    
    service:
      type: ClusterIP
      port: 3306
      nodePort: null
      annotations: {}

# Optional: extra labels or annotations
commonLabels: {}
commonAnnotations: {}
