replicaCount: 1

image:
  repository: sundayfagbuaro/flask-helm-deploy-img
  tag: 1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  host: containers.sunny.lab
  path: /myapp

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

database:
  host: myapp-mysql
  name: users_db
  port: 3306
  secretName: myapp-db-secret
  secretUserKey: DB_USER
  secretPasswordKey: DB_PASS

  mysql:
  auth:
    rootPassword: password
    database: users_db
    username: flaskuser
    password: password
  primary:
    persistence:
      enabled: false
      size: 8Gi
      storageClass: nfs-csi-databases
    service:
      type: ClusterIP
      port: 3306
      nodePort: null
      annotations: {}
