grafana:
  adminPassword: P@ssWord1
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - monitoring.sunny.lab
    path: /
    pathType: Prefix
  persistence:
    enabled: true
    storageClassName: nfs-csi-grafana-argocd
    accessModes:
      - ReadWriteOnce
    size: 5Gi

prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-csi-prometheus-argocd
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
