---
- name: Spectrum Scale installation on the nodes
  hosts: scale
  become: yes

  tasks:
    - name: Create staging directory
      file:
        path: /root/scale_install
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy Spectrum Scale package
      copy:
        src: /home/bobosunne/packages/Storage_Scale_Standard-5.2.3.7-x86_64-Linux-install
        dest: /root/scale_install/Storage_Scale_Standard-5.2.3.7-x86_64-Linux-install
        owner: root
        group: root
        mode: '0755'
    
    - name: Ensure installer is executable
      file:
        path: /root/scale_install/Storage_Scale_Standard-5.2.3.7-x86_64-Linux-install
        mode: '0755'
        state: file
      
    - name: Extract the installer # This extract the rpm files into /usr/lpp/mmfs/5.2.3.7
      shell: |
        cd /root/scale_install
        ./Storage_Scale_Standard-5.2.3.7-x86_64-Linux-install --silent

    - name: Install prerequisite packages for spectrum Scale RPMs
      dnf:
        name:
          - gcc
          - cpp
          - make
          - kernel-devel
          - kernel-headers
          - elfutils-libelf-devel
        state: present

#    - name: Install Spectrum Scale RPMs
#      dnf:
#        name: "/usr/lpp/mmfs/5.2.3.7/*.rpm"
#        disable_gpg_check: yes
#        state: present
    
    - name: Find RPMs to install
      find:
        paths: /usr/lpp/mmfs/5.2.3.7/gpfs_rpms
        patterns: "*.rpm"
      register: scale_rpms

#    - name: Install RPMs
#      dnf:
#        name: "{{ scale_rpms.files | map(attribute='path') | list }}"
#        state: present
    
    - name: Install Storage Scale RPMs excluding GUI
      dnf:
        name: >-
          {{
            scale_rpms.files
            | map(attribute='path')
            | reject('search', 'gpfs.gui')
            | reject('search', 'pmcollector')
            | list
          }}
        state: present
        disable_gpg_check: true