apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql_deploy.fullname" . }}-initdb
data:
{{- range $key, $value := .Values.initdbScripts }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- end }}