#flaskapp:
#  image:
#    repository: docker.io/sundayfagbuaro/k8s-deploy-demo:v1
#    tag: "v1"
#    pullPolicy: IfNotPresent
#  replicaCount: 

replicaCount: 1

image:
  repository: docker.io/sundayfagbuaro/flask-helm-deploy-img
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  name: flask-app
  port: 5000

mysql:
  host: flask-db
  port: 3306
  database: users_db
  existingSecret: mysql-secret   # Must contain mysql-username & mysql-root-password

resources: {}