---
- hosts: scale
  become: true
  tasks:
    - name: Generate SSH keys
      openssh_keypair:
        path: /home/bobosunne/.ssh/id_rsa
        type: rsa
        size: 4096
        owner: bobosunne
        group: bobosunne
    
    - name: Read public key
      slurp:
        src: /home/rocky/.ssh/id_rsa.pub
      register: pubkey
    
    - name: Add keys to authorized_keys
      authorized_key:
        user: bobosunne
        state: present
        key: "{{ hostvars[item]['pubkey']['content'] | b64decode }}"
      loop: "{{ groups['scale'] }}"