---
- hosts: scale
  become: true
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Enable chronyd
      service:
       name: chronyd
        state: started
        enabled: true