apiVersion: v1
kind: Service
metadata:
  name: {{ include "flaskapp.fullname" . }}
  labels:
    {{- include "flaskapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
  selector:
    {{- include "flaskapp.selectorLabels" . | nindent 4 }}
