image:
  repository: mysql
  tag: 8.0
  
replicas: 1

fullnameOverride: flask-db

persistence:
  enabled: true
  storageClassName: nfs-csi-flaskdb
  accessModes:
    - ReadWriteOnce
  size: 5Gi

service:
  name: flask-db
  port: 3306

secrets:
  existingSecret: mysql-secret

initdbScripts:
  init.sh: |
    #!/bin/bash
    set -e

    MYSQL_ROOT_PASSWORD=$(cat /run/secrets/mysql-root-password)
    MYSQL_USER=$(cat /run/secrets/mysql-username)
    MYSQL_PASSWORD=$(cat /run/secrets/mysql-password)

    mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
      CREATE DATABASE IF NOT EXISTS users_db;
      CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
      GRANT ALL PRIVILEGES ON users_db.* TO '${MYSQL_USER}'@'%';
      FLUSH PRIVILEGES;

      USE users_db;
      CREATE TABLE IF NOT EXISTS new_users (
        id INT AUTO_INCREMENT,
        f_name VARCHAR(30),
        l_name VARCHAR(30),
        address VARCHAR(30),
        phone VARCHAR(11),
        username VARCHAR(30),
        password VARCHAR(20),
        email VARCHAR(30),
        PRIMARY KEY(id)
      );
    EOSQL