[master]
k8s-master-dev ansible_host=10.10.10.14 ansible_user=bobosunne

[workers]
k8s-master-dev-1 ansible_host=10.10.1.15 ansible_user=bobosunne
k8s-master-dev-2 ansible_host=10.10.1.16 ansible_user=bobosunne

[kubernetes:children]
master
workers
