svms:
  - name: svm1
    root_volume: root_vol1
    aggregate: aggr1
    volumes:
      - name: vol_data1
        size: 100GB
        lun:
          name: lun_data1
          size: 10GB
        nfs_export: /vol_data1
        cifs_share:
          name: share_data1
          comment: "Automation Share 1"
  - name: svm2
    root_volume: root_vol2
    aggregate: aggr2
    volumes:
      - name: vol_data2
        size: 200GB
        lun:
          name: lun_data2
          size: 20GB
        nfs_export: /vol_data2
        cifs_share:
          name: share_data2
          comment: "Automation Share 2"

snapmirrors:
  - source_svm: svm1
    source_volume: vol_data1
    destination_svm: svm2
    destination_volume: vol_data2
    schedule: daily
