---
- hosts: master
  gather_facts: no
  become: yes
  roles:
    - role: monitoring
      vars:
        kubeconfig_path: /home/bobosunne/.kube/ansible-kubeconfig
  tasks:
    - name: All Kubernetes tasks on Ansible host
      delegate_to: localhost
